version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:4321@host.docker.internal:5432/clubedolivro?schema=public
      - REDIS_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://api.clubedolivro.clube
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
